name: coffee_api
description: Pull images of coffee from https://coffee.alexflipnote.dev/
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  http: ^0.13.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
