name: coffee
description: Very good coffee app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  bloc: ^8.1.0
  coffee_local_storage_api:
    path: packages/coffee_local_storage_api
  coffee_repository:
    path: packages/coffee_repository
  coffee_storage_repository:
    path: packages/coffee_storage_repository
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  path_provider: ^2.0.13

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
