name: coffee_local_storage_api
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  coffee_storage_api:
    path: ../coffee_storage_api
  file: ^6.1.4
  path: ^1.8.2

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
